/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing TransactionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TransactionsApiTests
    {
        private TransactionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TransactionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TransactionsApi
            //Assert.IsInstanceOfType(typeof(TransactionsApi), instance, "instance is a TransactionsApi");
        }

        /// <summary>
        /// Test ApiV1TransactionsGet
        /// </summary>
        [Test]
        public void ApiV1TransactionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string page = null;
            //string size = null;
            //string accountId = null;
            //string customerId = null;
            //string type = null;
            //string from = null;
            //string to = null;
            //instance.ApiV1TransactionsGet(page, size, accountId, customerId, type, from, to);
            
        }
        /// <summary>
        /// Test ApiV1TransactionsTransactionIdGet
        /// </summary>
        [Test]
        public void ApiV1TransactionsTransactionIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string transactionId = null;
            //instance.ApiV1TransactionsTransactionIdGet(transactionId);
            
        }
    }

}
