/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing VirtualNubansApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class VirtualNubansApiTests
    {
        private VirtualNubansApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VirtualNubansApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VirtualNubansApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VirtualNubansApi
            //Assert.IsInstanceOfType(typeof(VirtualNubansApi), instance, "instance is a VirtualNubansApi");
        }

        /// <summary>
        /// Test ApiV1VirtualNubansBySettlementAccountSettlementAccountIdGet
        /// </summary>
        [Test]
        public void ApiV1VirtualNubansBySettlementAccountSettlementAccountIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string settlementAccountId = null;
            //var response = instance.ApiV1VirtualNubansBySettlementAccountSettlementAccountIdGet(settlementAccountId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1VirtualNubansCloseAccountAccountIdDelete
        /// </summary>
        [Test]
        public void ApiV1VirtualNubansCloseAccountAccountIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ApiV1VirtualNubansCloseAccountAccountIdDelete(accountId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1VirtualNubansPost
        /// </summary>
        [Test]
        public void ApiV1VirtualNubansPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //var response = instance.ApiV1VirtualNubansPost(body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1VirtualNubansVirtualAccountIdGet
        /// </summary>
        [Test]
        public void ApiV1VirtualNubansVirtualAccountIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string virtualAccountId = null;
            //var response = instance.ApiV1VirtualNubansVirtualAccountIdGet(virtualAccountId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
