/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing WebhookApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WebhookApiTests
    {
        private WebhookApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WebhookApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WebhookApi
            //Assert.IsInstanceOfType(typeof(WebhookApi), instance, "instance is a WebhookApi");
        }

        /// <summary>
        /// Test ApiV1WebhooksGet
        /// </summary>
        [Test]
        public void ApiV1WebhooksGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string page = null;
            //string size = null;
            //var response = instance.ApiV1WebhooksGet(page, size);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1WebhooksPost
        /// </summary>
        [Test]
        public void ApiV1WebhooksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //var response = instance.ApiV1WebhooksPost(body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1WebhooksWebhookIdGet
        /// </summary>
        [Test]
        public void ApiV1WebhooksWebhookIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string webhookId = null;
            //var response = instance.ApiV1WebhooksWebhookIdGet(webhookId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
