/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Co.GetAnchor.Sdk.Client;

namespace Co.GetAnchor.Sdk.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAccountsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Fetch Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>Object</returns>
        Object ApiV1AccountsAccountIdGet (string accountId);

        /// <summary>
        /// Fetch Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApiV1AccountsAccountIdGetWithHttpInfo (string accountId);
        /// <summary>
        /// Fetch Account Balance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>Object</returns>
        Object ApiV1AccountsBalanceAccountIdGet (string accountId, string xAnchorKey = null);

        /// <summary>
        /// Fetch Account Balance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApiV1AccountsBalanceAccountIdGetWithHttpInfo (string accountId, string xAnchorKey = null);
        /// <summary>
        /// List Accounts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>Object</returns>
        Object ApiV1AccountsGet (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null);

        /// <summary>
        /// List Accounts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApiV1AccountsGetWithHttpInfo (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null);
        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>Object</returns>
        Object ApiV1AccountsPost (Object body = null, string contentType = null);

        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApiV1AccountsPostWithHttpInfo (Object body = null, string contentType = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Fetch Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApiV1AccountsAccountIdGetAsync (string accountId);

        /// <summary>
        /// Fetch Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsAccountIdGetAsyncWithHttpInfo (string accountId);
        /// <summary>
        /// Fetch Account Balance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApiV1AccountsBalanceAccountIdGetAsync (string accountId, string xAnchorKey = null);

        /// <summary>
        /// Fetch Account Balance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsBalanceAccountIdGetAsyncWithHttpInfo (string accountId, string xAnchorKey = null);
        /// <summary>
        /// List Accounts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApiV1AccountsGetAsync (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null);

        /// <summary>
        /// List Accounts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsGetAsyncWithHttpInfo (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null);
        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApiV1AccountsPostAsync (Object body = null, string contentType = null);

        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsPostAsyncWithHttpInfo (Object body = null, string contentType = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AccountsApi : IAccountsApi
    {
        private Co.GetAnchor.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountsApi(String basePath)
        {
            this.Configuration = new Co.GetAnchor.Sdk.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Co.GetAnchor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class
        /// </summary>
        /// <returns></returns>
        public AccountsApi()
        {
            this.Configuration = Co.GetAnchor.Sdk.Client.Configuration.Default;

            ExceptionFactory = Co.GetAnchor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountsApi(Co.GetAnchor.Sdk.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Co.GetAnchor.Sdk.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Co.GetAnchor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Co.GetAnchor.Sdk.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Co.GetAnchor.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Fetch Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>Object</returns>
        public Object ApiV1AccountsAccountIdGet (string accountId)
        {
             ApiResponse<Object> localVarResponse = ApiV1AccountsAccountIdGetWithHttpInfo(accountId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ApiV1AccountsAccountIdGetWithHttpInfo (string accountId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiV1AccountsAccountIdGet");

            var localVarPath = "/api/v1/accounts/{accountId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsAccountIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Fetch Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApiV1AccountsAccountIdGetAsync (string accountId)
        {
             ApiResponse<Object> localVarResponse = await ApiV1AccountsAccountIdGetAsyncWithHttpInfo(accountId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Fetch Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsAccountIdGetAsyncWithHttpInfo (string accountId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiV1AccountsAccountIdGet");

            var localVarPath = "/api/v1/accounts/{accountId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsAccountIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Fetch Account Balance 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>Object</returns>
        public Object ApiV1AccountsBalanceAccountIdGet (string accountId, string xAnchorKey = null)
        {
             ApiResponse<Object> localVarResponse = ApiV1AccountsBalanceAccountIdGetWithHttpInfo(accountId, xAnchorKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch Account Balance 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ApiV1AccountsBalanceAccountIdGetWithHttpInfo (string accountId, string xAnchorKey = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiV1AccountsBalanceAccountIdGet");

            var localVarPath = "/api/v1/accounts/balance/{accountId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (xAnchorKey != null) localVarHeaderParams.Add("x-anchor-key", this.Configuration.ApiClient.ParameterToString(xAnchorKey)); // header parameter
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsBalanceAccountIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Fetch Account Balance 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApiV1AccountsBalanceAccountIdGetAsync (string accountId, string xAnchorKey = null)
        {
             ApiResponse<Object> localVarResponse = await ApiV1AccountsBalanceAccountIdGetAsyncWithHttpInfo(accountId, xAnchorKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Fetch Account Balance 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsBalanceAccountIdGetAsyncWithHttpInfo (string accountId, string xAnchorKey = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiV1AccountsBalanceAccountIdGet");

            var localVarPath = "/api/v1/accounts/balance/{accountId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (xAnchorKey != null) localVarHeaderParams.Add("x-anchor-key", this.Configuration.ApiClient.ParameterToString(xAnchorKey)); // header parameter
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsBalanceAccountIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// List Accounts 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>Object</returns>
        public Object ApiV1AccountsGet (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null)
        {
             ApiResponse<Object> localVarResponse = ApiV1AccountsGetWithHttpInfo(xAnchorKey, size, accountType, page, customerId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Accounts 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ApiV1AccountsGetWithHttpInfo (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null)
        {

            var localVarPath = "/api/v1/accounts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (size != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "size", size)); // query parameter
            if (accountType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "accountType", accountType)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (customerId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "customerId", customerId)); // query parameter
            if (xAnchorKey != null) localVarHeaderParams.Add("x-anchor-key", this.Configuration.ApiClient.ParameterToString(xAnchorKey)); // header parameter
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// List Accounts 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApiV1AccountsGetAsync (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null)
        {
             ApiResponse<Object> localVarResponse = await ApiV1AccountsGetAsyncWithHttpInfo(xAnchorKey, size, accountType, page, customerId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Accounts 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAnchorKey"> (optional)</param>
        /// <param name="size"> (optional)</param>
        /// <param name="accountType"> (optional)</param>
        /// <param name="page"> (optional)</param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsGetAsyncWithHttpInfo (string xAnchorKey = null, int? size = null, string accountType = null, string page = null, string customerId = null)
        {

            var localVarPath = "/api/v1/accounts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (size != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "size", size)); // query parameter
            if (accountType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "accountType", accountType)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (customerId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "customerId", customerId)); // query parameter
            if (xAnchorKey != null) localVarHeaderParams.Add("x-anchor-key", this.Configuration.ApiClient.ParameterToString(xAnchorKey)); // header parameter
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>Object</returns>
        public Object ApiV1AccountsPost (Object body = null, string contentType = null)
        {
             ApiResponse<Object> localVarResponse = ApiV1AccountsPostWithHttpInfo(body, contentType);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ApiV1AccountsPostWithHttpInfo (Object body = null, string contentType = null)
        {

            var localVarPath = "/api/v1/accounts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApiV1AccountsPostAsync (Object body = null, string contentType = null)
        {
             ApiResponse<Object> localVarResponse = await ApiV1AccountsPostAsyncWithHttpInfo(body, contentType);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="Co.GetAnchor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiV1AccountsPostAsyncWithHttpInfo (Object body = null, string contentType = null)
        {

            var localVarPath = "/api/v1/accounts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (contentType != null) localVarHeaderParams.Add("Content-Type", this.Configuration.ApiClient.ParameterToString(contentType)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (apikeyAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1AccountsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

    }
}
