/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Co.GetAnchor.Sdk.Api;
using Co.GetAnchor.Sdk.Model;
using Co.GetAnchor.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing CustomerIdDocumentIdBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerIdDocumentIdBodyTests
    {
        // TODO uncomment below to declare an instance variable for CustomerIdDocumentIdBody
        //private CustomerIdDocumentIdBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerIdDocumentIdBody
            //instance = new CustomerIdDocumentIdBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerIdDocumentIdBody
        /// </summary>
        [Test]
        public void CustomerIdDocumentIdBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerIdDocumentIdBody
            //Assert.IsInstanceOfType<CustomerIdDocumentIdBody> (instance, "variable 'instance' is a CustomerIdDocumentIdBody");
        }


        /// <summary>
        /// Test the property 'FileData'
        /// </summary>
        [Test]
        public void FileDataTest()
        {
            // TODO unit test for the property 'FileData'
        }
        /// <summary>
        /// Test the property 'TextData'
        /// </summary>
        [Test]
        public void TextDataTest()
        {
            // TODO unit test for the property 'TextData'
        }

    }

}
