/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing AccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccountsApiTests
    {
        private AccountsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccountsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccountsApi
            //Assert.IsInstanceOfType(typeof(AccountsApi), instance, "instance is a AccountsApi");
        }

        /// <summary>
        /// Test ApiV1AccountsAccountIdGet
        /// </summary>
        [Test]
        public void ApiV1AccountsAccountIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ApiV1AccountsAccountIdGet(accountId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1AccountsBalanceAccountIdGet
        /// </summary>
        [Test]
        public void ApiV1AccountsBalanceAccountIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string xAnchorKey = null;
            //var response = instance.ApiV1AccountsBalanceAccountIdGet(accountId, xAnchorKey);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1AccountsGet
        /// </summary>
        [Test]
        public void ApiV1AccountsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAnchorKey = null;
            //int? size = null;
            //string accountType = null;
            //string page = null;
            //string customerId = null;
            //var response = instance.ApiV1AccountsGet(xAnchorKey, size, accountType, page, customerId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1AccountsPost
        /// </summary>
        [Test]
        public void ApiV1AccountsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //string contentType = null;
            //var response = instance.ApiV1AccountsPost(body, contentType);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
