/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing CounterPartyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CounterPartyApiTests
    {
        private CounterPartyApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CounterPartyApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CounterPartyApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CounterPartyApi
            //Assert.IsInstanceOfType(typeof(CounterPartyApi), instance, "instance is a CounterPartyApi");
        }

        /// <summary>
        /// Test ApiV1BanksGet
        /// </summary>
        [Test]
        public void ApiV1BanksGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAnchorKey = null;
            //var response = instance.ApiV1BanksGet(xAnchorKey);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1CounterpartiesCounterpartyidGet
        /// </summary>
        [Test]
        public void ApiV1CounterpartiesCounterpartyidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string counterpartyid = null;
            //var response = instance.ApiV1CounterpartiesCounterpartyidGet(counterpartyid);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1CounterpartiesGet
        /// </summary>
        [Test]
        public void ApiV1CounterpartiesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string page = null;
            //string size = null;
            //var response = instance.ApiV1CounterpartiesGet(page, size);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1CounterpartiesPost
        /// </summary>
        [Test]
        public void ApiV1CounterpartiesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //var response = instance.ApiV1CounterpartiesPost(body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1PaymentsVerifyAccountBankIdAccountNumberGet
        /// </summary>
        [Test]
        public void ApiV1PaymentsVerifyAccountBankIdAccountNumberGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string bankId = null;
            //int? accountNumber = null;
            //var response = instance.ApiV1PaymentsVerifyAccountBankIdAccountNumberGet(bankId, accountNumber);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
