/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing CustomersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CustomersApiTests
    {
        private CustomersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CustomersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CustomersApi
            //Assert.IsInstanceOfType(typeof(CustomersApi), instance, "instance is a CustomersApi");
        }

        /// <summary>
        /// Test ApiV1CustomersCustomerIdGet
        /// </summary>
        [Test]
        public void ApiV1CustomersCustomerIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customerId = null;
            //string xAnchorKey = null;
            //var response = instance.ApiV1CustomersCustomerIdGet(customerId, xAnchorKey);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1CustomersGet
        /// </summary>
        [Test]
        public void ApiV1CustomersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string type = null;
            //string page = null;
            //int? size = null;
            //var response = instance.ApiV1CustomersGet(type, page, size);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1CustomersPost
        /// </summary>
        [Test]
        public void ApiV1CustomersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //string contentType = null;
            //string xAnchorKey = null;
            //var response = instance.ApiV1CustomersPost(body, contentType, xAnchorKey);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1CustomersUpdateCustomerIdPut
        /// </summary>
        [Test]
        public void ApiV1CustomersUpdateCustomerIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customerId = null;
            //Object body = null;
            //string contentType = null;
            //string xAnchorKey = null;
            //instance.ApiV1CustomersUpdateCustomerIdPut(customerId, body, contentType, xAnchorKey);
            
        }
    }

}
