/* 
 * Anchor API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Co.GetAnchor.Sdk.Client;
using Co.GetAnchor.Sdk.Api;

namespace Co.GetAnchor.Sdk.Test
{
    /// <summary>
    ///  Class for testing EventApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EventApiTests
    {
        private EventApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EventApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EventApi
            //Assert.IsInstanceOfType(typeof(EventApi), instance, "instance is a EventApi");
        }

        /// <summary>
        /// Test ApiV1EventsEventIdGet
        /// </summary>
        [Test]
        public void ApiV1EventsEventIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string eventId = null;
            //var response = instance.ApiV1EventsEventIdGet(eventId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ApiV1EventsGet
        /// </summary>
        [Test]
        public void ApiV1EventsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? size = null;
            //string type = null;
            //int? page = null;
            //var response = instance.ApiV1EventsGet(size, type, page);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
